server.port: 7281

solon.app:
  name: gritapi
  group: grit

solon.cloud.water:
  server: "waterapi:9371"
  config:
    load: "grit.yml"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"


