

solon.app:
  name: gritadmin
  group: grit
  title: "跨系统通用管理平台"


solon.cloud.water:
  server: "waterapi:9371"
  config:
    load: "grit.yml,gritadmin.yml"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"


