server.port: 7282

solon.app:
  name: gritadmin
  group: grit
  title: "GRIT 权限管理"


solon.cloud.water:
  server: "waterapi:9371"
  config:
    load: "grit.yml"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"


gritadmin:
  user: admin
  password: SykSYLWN9WTpzCHq