version: '3'

# 部署指南：
# 1.把配置里的 grit.db.* 换成真实的 grit db 配置。并启动
# 2.打开 http://localhost:7281/grit/ ,可进入权限管理控制台
# 3.打开 http://localhost:7281/ ，可查看主体的权限效果

services:
  gritdock:
    image: noearorg/gritdock:1.2.3
    container_name: gritdock
    environment:
      - grit.db.schema=grit
      - grit.db.server=mysql.grit.io:3306
      - grit.db.password=123456
      - grit.db.username=demo
      - grit.token=B6uWZDYUm4kMscdEAERXQ2wMBW1nLL0j   #rpc连接令牌（只要前后能对起来，随便输）
      - gritadmin.password=SykSYLWN9WTpzCHq           # Grit 管理密码
      - TZ=Asia/Shanghai
    ports:
      - 7281:7281
