server.port: 8081

solon.app:
  name: "gritexample1-server"
  group: "grit"
  title: "DEMO-SERVER"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"

grit:
  db.schema: grit
  db.server: localhost:3306
  db.username: root
  db.password: 123456
  cache.driverType: local
  rpc.token: "B6uWZDYUm4kMscdEAERXQ2wMBW1nLL0j"

gritadmin:
  user: admin
  password: SykSYLWN9WTpzCHq
  title: "Grit - 控制台"
