server.port: 8081

solon.app:
  name: "grit-example3"
  group: "grit"
  title: "跨系统通用管理平台"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: "WARN"
  "com.zaxxer.hikari.*":
    level: "WARN"

# server, client 同时存在时；client 不需要配置，自动切换为 jdbc 模式

grit:
  db.schema: grit
  db.server: localhost:3306
  db.username: root
  db.password: 123456
  cache.driverType: local
  rpc.token: "B6uWZDYUm4kMscdEAERXQ2wMBW1nLL0j"

gritadmin:
  user: admin
  password: SykSYLWN9WTpzCHq
  title: "Grit - 控制台"
