
solon.app:
  name: "gritdock"
  group: "grit"
  title: "跨系统通用管理平台"


#  可以换成任何 solon cloud 的其它配置服务组件
solon.cloud.water:
  server: "waterapi:9371"
  config:
    load: "gritclient.yml,gritdock.yml"

gritdock:
  env: "演示环境"
  title: "演示环境-跨系统通用管理平台"

