
solon.app:
  name: "stonedock"
  group: "stone"
  title: "跨系统通用管理平台"

solon.cloud.water:
  server: "water"
  config:
    load: "stone.yml,stonedock.yml"

stonedock:
  env: "演示环境"
  title: "演示环境-跨系统通用管理平台"

