
solon.app:
  name: "gritdock"
  group: "grit"
  title: "跨系统通用管理平台"

solon.cloud.water:
  server: "water"
  config:
    load: "grit.yml,gritdock.yml"

gritdock:
  env: "演示环境"
  title: "演示环境-跨系统通用管理平台"

